baseURL: "https://jacobcornelius.com"
languageCode: "en-us"
title: "Jacob Cornelius"
theme: "stack"
publishDir: "public"

params:
  HomeIntro:
    Title: "Welcome to my site"
    Content: "Your custom homepage content here."

